Enhance Dockerfiles to Utilize install.sh Script
openshift-eng/art-dashboard-server pull request #112
Opened 2023-11-16 16:11 UTC by MartinPl0

Adjusted Dockerfile.base and Dockerfile.update to optimize the use of the install.sh script from art-tools. This change ensures proper execution of the script within the Docker build process, improving dependency management and aligning with our updated build strategy. The modifications include updating pip before the script execution and ensuring compatibility in the Docker environment.

2023-11-20 09:58 UTC, vfreex reviewed
/lgtm

2023-11-20 15:41 UTC, mbiarnes commented
/approve

2023-11-20 16:45 UTC, ashwindasr commented
/hold

@MartinPl0 can you sync the changes from the art-bot PR as well?

2023-11-20 16:59 UTC, ashwindasr requested changes

2023-11-20 16:59 UTC, ashwindasr commented on Dockerfile.base
> +RUN dnf install -y git python3.8 python3-pip \
Python is already installed in the container, so this line will be redundant

2023-11-20 16:59 UTC, ashwindasr commented on Dockerfile.base
> + && pip3 install --upgrade pip \
Lets move this to the top of the file like art-bot's

2023-11-20 16:59 UTC, ashwindasr commented on Dockerfile.base
> +WORKDIR /art-tools
Lets not set a `WORKDIR` here

2023-11-21 20:41 UTC, ashwindasr commented on Dockerfile.update
> +WORKDIR /workspaces/art-dash
Need to match the one in Dockerfile.base

2023-11-21 22:52 UTC, ashwindasr approved these changes

2023-11-21 22:53 UTC, merged